version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: taskforge_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taskforge_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskforge_backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATIONMS=${JWT_EXPIRATION_MS}
    depends_on:
      - mysql_db
    networks:
      - taskforge_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskforge_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - taskforge_network

networks:
  taskforge_network:
    driver: bridge

volumes:
  mysql_data:
