server.port=8080

spring.application.name=taskforge
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}
# Update username and password above according to your local MySQL setup

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
taskforge.app.jwtSecret=${JWT_SECRET:TaskForgeSecretKeyThatNeedsToBeLongEnoughForHS256AlgorithmOfAtLeast256Bits12345}
taskforge.app.jwtExpirationMs=${JWT_EXPIRATIONMS:86400000}

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO
